-- 1. Create the comments table if it doesn't exist
create table if not exists comments (
  id bigint generated by default as identity primary key,
  book_id bigint references books(id) on delete cascade not null,
  content text not null,
  author_name text not null,
  is_author boolean default false,
  parent_id bigint references comments(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add genre column to books table if it doesn't exist
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'books' and column_name = 'genre') then
        alter table books add column genre text default 'General';
    end if;
end $$;

-- 3. Enable RLS on comments
alter table comments enable row level security;

-- 4. Create policies for comments (drop existing first to avoid errors if re-running)
drop policy if exists "Comments are viewable by everyone" on comments;
create policy "Comments are viewable by everyone" on comments for select using ( true );

drop policy if exists "Everyone can insert comments" on comments;
create policy "Everyone can insert comments" on comments for insert with check ( true );

drop policy if exists "Anyone can update specific fields" on comments;
create policy "Anyone can update specific fields" on comments for update using ( true );
