-- Create a table for comments
create table comments (
  id bigint generated by default as identity primary key,
  book_id bigint references books(id) on delete cascade not null,
  content text not null,
  author_name text not null,
  is_author boolean default false,
  parent_id bigint references comments(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table comments enable row level security;

-- Create a policy that allows everyone to read comments
create policy "Comments are viewable by everyone"
  on comments for select
  using ( true );

-- Create a policy that allows everyone to insert comments (anon users)
create policy "Everyone can insert comments"
  on comments for insert
  with check ( true );

-- Create a policy that allows the author (authenticated or specific logic) or anyone to delete (simplify for now)
-- ideally we need auth, but for now we follow the 'is_author' flag trusting the client logic (not secure but fits the requested scope)
create policy "Anyone can update specific fields"
  on comments for update
  using ( true );
