-- 1. Create table for storing Anonymous Browser Tokens (FCM Tokens)
create table fcm_tokens (
  browser_id uuid primary key, -- Generated UUID stored in user's LocalStorage
  fcm_token text not null,     -- The token from Firebase
  device_info text,            -- Optional: "Chrome on Windows", "Safari on iPhone"
  last_active timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- Enable RLS for fcm_tokens
alter table fcm_tokens enable row level security;

-- Policy: Allow anyone to insert their token (needed for anon users)
create policy "Anyone can register token"
  on fcm_tokens for insert
  with check ( true );

-- Policy: Users can only update their own token (based on browser_id)
-- practically difficult to enforce strictly without auth, but we trust the browser_id claim for now
create policy "Anyone can update tokens"
  on fcm_tokens for update
  using ( true );

create policy "Anyone can read tokens"
  on fcm_tokens for select
  using ( true );


-- 2. Create table for Following Authors
create table author_follows (
  id bigint generated by default as identity primary key,
  follower_browser_id uuid references fcm_tokens(browser_id) on delete cascade,
  followed_author_name text not null,
  created_at timestamp with time zone default now(),
  -- Prevent duplicate follows
  unique(follower_browser_id, followed_author_name)
);

-- Enable RLS for follows
alter table author_follows enable row level security;

create policy "Anyone can follow"
  on author_follows for insert
  with check ( true );

create policy "Anyone can unfollow"
  on author_follows for delete
  using ( true );

create policy "Anyone can view follows"
  on author_follows for select
  using ( true );


-- 3. Update Comments table to track the browser_id of the commenter
-- This links a comment to a specific device/user for reply notifications
alter table comments 
add column browser_id uuid references fcm_tokens(browser_id) on delete set null;
