-- Tabel untuk menyimpan emoji reactions dari pembaca per chapter
CREATE TABLE IF NOT EXISTS reactions (
  id bigint generated by default as identity primary key,
  book_id bigint references books(id) on delete cascade not null,
  chapter_id bigint, -- null = buku lama (tidak per-chapter)
  browser_id text not null, -- Identitas anonim pembaca
  emoji text not null default '😊', -- Emoji yang dipilih
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Satu browser hanya bisa bereaksi sekali per chapter/buku
  UNIQUE(book_id, chapter_id, browser_id)
);

-- Enable Row Level Security
ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;

-- Semua orang bisa baca (untuk hitung total)
CREATE POLICY "Reactions viewable by everyone" ON reactions FOR SELECT USING (true);

-- Semua orang bisa insert (anon readers)
CREATE POLICY "Anyone can insert reactions" ON reactions FOR INSERT WITH CHECK (true);

-- Hanya creator reaction itu sendiri yang bisa delete (berdasarkan browser_id, logic di client)
CREATE POLICY "Anyone can delete own reactions" ON reactions FOR DELETE USING (true);
